[project]
name = "wtftw_core"
version = "0.3.3"
authors = ["Simon Wollwage"]
edition = "2018"

[dependencies]
bitflags = "*"
serde_json = "*"
log = "*"
simplelog = "*"
libc = "*"
dylib = "*"
dirs = "*"

[lib]
name = "wtftw_core"
path = "src/wtftw.rs"
crate-type = ["rlib"]
